In [4]:
# Active Learning - Uncertainty Sampling

import numpy as np
import pandas as pd
import os
from imblearn.ensemble import BalancedBaggingClassifier
from sklearn.ensemble import RandomForestClassifier
import joblib
from sklearn.calibration import CalibratedClassifierCV
from warnings import simplefilter
from sklearn.metrics import confusion_matrix, classification_report, f1_score

from google.colab import drive


simplefilter(action='ignore', category=FutureWarning)

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.ensemble.bagging module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported fro

In [5]:
# Συνδέομαι στο google drive για να μπορώ να αποθηκεύω και να ανακτώ μοντέλα από εκεί
drive.mount('/content/drive/')

Mounted at /content/drive/


In [6]:
# Καθορίζω την διαδρομή στο google drive και φορτώνω στην μνήμη το σύνολο των δεδομένων
path = 'drive/My Drive/bank_credit'
dt = pd.read_csv(os.path.join(path, 'creditcard.csv'))

In [7]:
# Επισκόπηση λίγων δεδομένων των δύο κλάσεων
a = dt.loc[dt['Class']==0].sample(3)
b = dt.loc[dt['Class']==1].sample(5)
c = pd.concat([a,b])
c

Time        V1        V2  ...       V28  Amount  Class
88243    62055.0 -0.823670  0.975735  ...  0.055759   39.15      0
240818  150762.0  2.008927 -2.263022  ... -0.017307  122.00      0
240459  150610.0 -1.295840  1.755734  ...  0.017319   27.76      0
92777    64093.0 -6.133987  2.941499  ...  0.310195  294.90      1
149869   92092.0 -1.108478  3.448953  ...  0.208830   18.00      1
39183    39729.0 -0.964567 -1.643541  ... -0.164500  776.83      1
140786   83934.0 -0.433222  2.428379  ...  0.541148    1.00      1
99506    67150.0 -1.824295  0.403327  ...  0.252713  489.71      1

[8 rows x 31 columns]

In [8]:
# Δημιουργώ ένα χαρακτηριστικό πυκνότητας συναλλαγών (Density) και ένα πραγματικής ώρας (Actual Time)
# θεωρώντας ότι μπορεί να υπάρχει κάποια συσχέτιση με τις κακόβουλες κινήσεις
# Ενώ παράλληλα διαγράφω το χαρακτηριστικό Time
period = 30 * 60 # secs
half_period = int(period / 2)
a = np.histogram(dt['Time'], bins=np.linspace(0, 172800, 172801))[0]

density48h = [np.mean(a[[j % 172800 for j in range(-half_period, +half_period)]])]
for i in range(1, len(a)):
  density48h.append(density48h[-1] + (a[(i + half_period - 1) % 172800] - a[(i - half_period) % 172800]) / period)

density48h = np.array(density48h)
density48h = density48h / density48h.max()

dt['Density'] = density48h[dt['Time'].astype(int).values]
dt['Density'].reset_index(drop=True)
dt['Actual_Time'] = dt['Time'].apply(lambda x: np.mod(x, 86400) / 86400)

dt.drop('Time', inplace=True, axis='columns')

In [9]:
# Μετατρέπω το χαρακτηριστικό Amount με λογαριθμική κανονικοποίηση
amounts = dt['Amount'].copy()
dt['Amount'] = np.log(dt['Amount']+2)

In [10]:
# Χωρίζω το σύνολο δεδομένων σε εκπαίδευσης, επικύρωσης και ελέγχου
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
seed = 0

x_tr, x_te, y_tr, y_te = train_test_split(dt.loc[:, dt.columns != 'Class'], dt['Class'], test_size=.3, random_state=seed)

va_size = int(len(x_tr) * .2)
x_tr, x_UN = x_tr[:va_size], x_tr[va_size:]
y_tr, y_UN = y_tr[:va_size], y_tr[va_size:]

print(x_tr.shape, x_UN.shape, x_te.shape)

(39872, 31) (159492, 31) (85443, 31)


In [11]:
# Δημιουργία ενός αριθμού από υποσύνολα δεδομένων τα οποία έχουν ίσο αριθμό παραδειγμάτων των δύο κλάσεων.
# Με αυτά εκπαιδεύονται μοντέλα Random Forest και η έκδσοση απόφασης γίνεται με ψηφοφορία.
# Το bagging μοντέλο εκπαιδεύεται και αποθηκεύεται, ώστε να μην χρειάζεται σε κάθε εκτέλεση του notebook

# y0 = y_tr[y_tr==0]
# x0 = x_tr[y_tr==0]

# y1 = y_tr[y_tr==1]
# x1 = x_tr[y_tr==1]

# ln = len(y1)
# number_of_subsets = 200

# print(f'iso {number_of_subsets}...')
# mod_iso = BalancedBaggingClassifier(base_estimator=RandomForestClassifier(n_estimators=200), n_estimators=number_of_subsets)
# model_iso = CalibratedClassifierCV(base_estimator=mod_iso, cv=3, method='isotonic')
# model_iso.fit(x_tr, y_tr)

# joblib.dump(model_iso, path + '/iso_bal_bag_rf_200_gini_200_active_learning.joblib')

In [12]:
# Ανάκληση του εκπαιδευμένου μοντέλου και υπολογισμός προβλέψεων στο σύνολο ελέγχου

model_iso = joblib.load(path + '/iso_bal_bag_rf_200_gini_200_active_learning.joblib')

y_preds = model_iso.predict_proba(x_te.to_numpy())

y_preds = y_preds.argmax(axis=1)

print(confusion_matrix(y_te, y_preds).T)
print()
print(classification_report(y_te, y_preds))


[[85279    33]
 [   17   114]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.87      0.78      0.82       147

    accuracy                           1.00     85443
   macro avg       0.93      0.89      0.91     85443
weighted avg       1.00      1.00      1.00     85443



In [ ]:
# Πρόβλεψη των καλιμπραρισμένων πιθανοτήτων για όλα τα μη ετικετοποιημένα δεδομένα και επιλογή των 50000 πιο αβέβαιων

# cost = 5000
# cost_per_example = 0.1

# preds = model_iso.predict_proba(x_UN.to_numpy())

# idx = np.argsort(np.abs(preds[:,0].flatten() - 0.5))[:int(cost/cost_per_example)]
 

In [ ]:
# Εκπαίδευση του μοντέλου με τα νέα επαυξημένα δεδομένα και αποθήκευσή του ώστε να μην επανεκπαιδεύεται σε κάθε νέα εκκίνηση του notebook

# x_ = np.vstack([x_UN.to_numpy()[idx], x_tr])
# y_ = y_UN.to_numpy()[idx].tolist() + y_tr.to_list()

# mod_iso_ = BalancedBaggingClassifier(base_estimator=RandomForestClassifier(n_estimators=200), n_estimators=number_of_subsets)
# model_iso_ = CalibratedClassifierCV(base_estimator=mod_iso_, cv=3, method='isotonic')
# model_iso_.fit(x_, y_)

# joblib.dump(model_iso_, path + '/iso_bal_bag_rf_200_gini_200_active_learning_uncertainty.joblib')


In [14]:
# Ανάκληση του αποθηκευμένου μοντέλου και πρόβλεψη των κατηγοριών των παραδειγμάτων ελέγχου
# Αυτή η προσπάθεια δεν δούλεψε καλά. Έριξε την ακρίβεια του μοντέλου για τα αρνητικά παραδείγματα η επέκταση των δεδομένων με μία μόνο εκτίμηση

model_iso_ = joblib.load(path + '/iso_bal_bag_rf_200_gini_200_active_learning_uncertainty.joblib')

y_preds_ = model_iso_.predict_proba(x_te.to_numpy())

y_preds_ = y_preds_.argmax(axis=1)

print(confusion_matrix(y_te, y_preds_).T)
print()
print(classification_report(y_te, y_preds_))

[[85283    44]
 [   13   103]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.89      0.70      0.78       147

    accuracy                           1.00     85443
   macro avg       0.94      0.85      0.89     85443
weighted avg       1.00      1.00      1.00     85443



In [ ]:
# Σταδιακή επέκταση των δεδομένων εκπαίδευσης σε 10 βήματα (ανά 5000 δείγματα) και αποθήκευση
# των επιμέρους εκπαιδευμένων μοντέλων για να μην επανεκπαιδεύονται σε κάθε επανεκκίνηση του notebook

# cost = 5000
# cost_per_example = 0.1


# sps = np.linspace(0, int(cost/cost_per_example), 11)
# x_rest = x_UN.to_numpy()
# y_rest = y_UN.to_numpy()
# x_ = x_tr.to_numpy()
# y_ = y_tr.to_numpy()

# for i in range(10):
#   print(f'{i+1}/10...')
#   sp = int(sps[i+1] - sps[i])

#   preds = model_iso.predict_proba(x_rest)

#   idx = np.argsort(np.abs(preds[:,0].flatten() - 0.5))[:sp]

#   x_ = np.vstack([x_rest[idx], x_])
#   y_ = np.array(y_rest[idx].tolist() + y_.tolist())

#   mod_iso_ = BalancedBaggingClassifier(base_estimator=RandomForestClassifier(n_estimators=200), n_estimators=number_of_subsets)
#   model_iso_ = CalibratedClassifierCV(base_estimator=mod_iso_, cv=3, method='isotonic')
#   model_iso_.fit(x_, y_)

#     joblib.dump(model_iso_, path + f'/iso_bal_bag_rf_200_gini_200_active_learning_uncertainty_{i}.joblib')

#   x_rest = np.delete(x_rest, idx, axis=0)
#   y_rest = np.delete(y_rest, idx, axis=0)

In [15]:
# Ανάκληση των αποθηκευμένων μοντέλων με τα σταδιακά αυξανόμενα δεδομένα και εκτύπωση στατιστικών
# Παρατηρείται μια μηδαμινή πτώση στα αρνητικά παραδείγματα της τάξης του 3.5x10^-5  και μια σημαντική
# βελτίωση στα θετικά παραδείγματα, της τάξης του 20%

for i in range(10):
  model_iso_ = joblib.load(path + f'/iso_bal_bag_rf_200_gini_200_active_learning_uncertainty_{i}.joblib')

  y_preds_ = model_iso_.predict_proba(x_te.to_numpy())

  y_preds_ = y_preds_.argmax(axis=1)

  print(f'Μετά από πρόσθεση {i+1}x5000 παραδειγμάτων...')
  print(confusion_matrix(y_te, y_preds_).T)
  print()
  print(classification_report(y_te, y_preds_))
  print(50*'-')

Μετά από πρόσθεση 1x5000 παραδειγμάτων...
[[85279    32]
 [   17   115]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.87      0.78      0.82       147

    accuracy                           1.00     85443
   macro avg       0.94      0.89      0.91     85443
weighted avg       1.00      1.00      1.00     85443

--------------------------------------------------
Μετά από πρόσθεση 2x5000 παραδειγμάτων...
[[85279    34]
 [   17   113]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.87      0.77      0.82       147

    accuracy                           1.00     85443
   macro avg       0.93      0.88      0.91     85443
weighted avg       1.00      1.00      1.00     85443

--------------------------------------------------
Μετά από πρόσθεση 3x5000 παραδειγμάτων...
[[85278    34]
 [   18   113]]

              precisio